FROM node:22-alpine

WORKDIR /app
ENV DATABASE_URL="postgresql://postgres:postgres@db:5432/test?schema=public&sslmode=disable&connect_timeout=10"

COPY package*.json ./
RUN npm ci --omit=optional || npm install
COPY prisma.config.ts ./
COPY tsconfig.json ./
COPY prisma/ ./prisma/
COPY src/catalog/ ./src/catalog/
COPY src/shared/ ./src/shared/
RUN npx prisma generate
EXPOSE 3001

CMD npx tsx src/catalog/index.ts
