FROM node:22-alpine

WORKDIR /app
ENV DATABASE_URL="postgresql://postgres:postgres@db:5432/test?schema=public&sslmode=disable&connect_timeout=10"

COPY package*.json ./
RUN npm ci --omit=optional || npm install
COPY prisma.config.ts ./
COPY tsconfig.json ./
COPY prisma/ ./prisma/
COPY src/cart/ ./src/cart/
COPY src/shared/ ./src/shared/
RUN npx prisma generate
EXPOSE 3000

CMD npx prisma db push && npx tsx src/cart/index.ts
