-- CreateTable
CREATE TABLE "cart" (
    "id" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "total" DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
